### ISSUE TITLE
プレイヤーの行動の制限など最終調整

### ISSUE THREAD

**Issue by ZOIChannel** [ZOIChannel/HideAndSeekPlugin#16]
1. **[完了]** 落下ダメージの無効化
2. **[完了]** アイテムのドロップをキャンセル
3. **[不要]** ブロック解除・キルのアイテムを同じにしたほうが使いやすい?
4. **[不要]** 花火が飛ばずにその場で爆発しているので、上に飛ばす
5. **[完了]** 生存者がいた場合そこに防具立てを設置、発光させる(次のゲームのスタート時に消去) ←できれば
6. **[完了]** ゲーム終了時にチャット欄に勝利陣営を書く、生存者がいればその名前を書く
7. **[完了]** Vault? と連携し、勝ち負けに応じてポイントを与える
8. **[完了]** そのポイントでブロックの選択肢を増やせるようにする
9. **[完了]** 左クリックで見破るとき、効果音を出す
10. **[完了]** フェンスなど立方体でないブロックに近づいた状態でブロック化するとブロックを置き換えてしまう
11. **[完了]** ゲーム中の生存状態をTabキーで確認できるようにする
12. **[完了]** サーバーログイン時にゲームの簡単な説明とコピーライトを出す

**Comment by ZOIChannel** [comment]
とりあえず1、2、4、6をやります
@ryokno08 3についてはどうしますか?

**Comment by ZOIChannel** [comment]
9. 左クリックで見破るとき、効果音を出す

これもやります

**Comment by ryosuke0818** [comment]
３についてはわざとやりづらくしています
右クリックと左クリックを連打するだけで捕まえられるのを防ぐためです
４に関してもわざとです
捕まえたということをすぐに鬼側に知らせるための演出です

**Comment by ryosuke0818** [comment]
４に関してはこれよりいい演出があれば変更していただいて構いません
例）効果音とともに全員にメッセージを送る

**Comment by ryosuke0818** [comment]
５に関してはどのタイミングで光らせますか？

**Comment by ryosuke0818** [comment]
７に関してはConfigでお金をいくら与えるか、決めれるようにした方が良さそうです

**Comment by ryosuke0818** [comment]
個人的に４に関して捕まえた直後の花火の音が音ハメっぽく気持ちいいです

**Comment by ZOIChannel** [comment]
なるほど
5は、ゲーム終了時に生存プレイヤー位置に光る防具立てを設置、次のゲームの開始時に防具立てを消去、という想定です

**Comment by ZOIChannel** [comment]
5番やります

**Comment by ryosuke0818** [comment]
７やっときます

**Comment by ZOIChannel** [comment]
11、12はやります
明日になりそうですが

**Comment by ryosuke0818** [comment]
７できました（テスト済み）

**Comment by ryosuke0818** [comment]
８できそうですか？ @ZOIChannel

**Comment by ryosuke0818** [comment]
８、ブロックの候補は作っておくのでGUIをお願いします

**Comment by ryosuke0818** [comment]
getPlayerUsableBlocks()から、プレイヤーが変身できるブロックを取得できるようにしておきました。
あとはこれをGUIに並べてクリックしたらブロックを変更するようにするだけです。
@ZOIChannel
