### ISSUE TITLE
自分の名前がたくさん表示された

### ISSUE THREAD

**Issue by ryosuke0818** [ZOIChannel/HideAndSeekPlugin#19]
![スクリーンショット 2021-08-21 17 05 52 2](https://user-images.githubusercontent.com/36810876/130315376-c90e879f-0a82-4208-8376-dcaee5c2d415.png)

**Comment by ZOIChannel** [comment]
僕の場合は2こでした

**Comment by ZOIChannel** [comment]
サブ垢のほうではプレイヤー名のないやつが2つでした
