### ISSUE TITLE
GUIをひらいてもブロックを選択できないバグがある

### ISSUE THREAD

**Issue by yokmama** [ZOIChannel/HideAndSeekPlugin#22]

**Comment by ZOIChannel** [comment]
これ、ただ複数人が同時に開いたときという条件では再現できませんでした
ただし、FallingBlockの状態でインベントリを開き、ブロックが固まってからインベントリをクリックした場合反応しなかったので、とりあえずこれを修正します
もしかするとこれを誤認していただけかもしれません

**Comment by ryosuke0818** [comment]
そういえば、HiderにBlockGuiを持たせていたみたいなんですが、Hiderのインスタンス生成時にGameを渡しているのが良くないなと思ってGameにBlockGuiを持たせるように変更しました。
今回の件と関係ないかもしれませんがね

**Comment by ryosuke0818** [comment]
GameにBlockGuiを持たせるというのは、Map<UUID, BlockGui>を生成してそこにBlockGuiを入れているということです。

**Comment by ZOI-dayo** [comment]
わかりました
