### ISSUE TITLE
Configの書き換えが直接ファイルの修正のみなので、コマンドで変更できるようにしたほうがいい

### ISSUE THREAD

**Issue by yokmama** [ZOIChannel/HideAndSeekPlugin#29]

**Comment by yokmama** [comment]
Configの書き換えはできていました。
SeekerRateが、Intで０〜１００なのに

Game:235
        int seekerRate = configLoader.getInt("seekerRate");
        int seekerCount = (int) Math.ceil(gamePlayers.size() / (float) seekerRate);

ここの計算で、そのままつかっているのが原因だとおもいます

**Comment by ZOIChannel** [comment]
コンフィグ変更コマンドの実装まだだった
