### ISSUE TITLE
プレイヤーが動かなくなって数秒たったことを通知するイベント処理の実装

### ISSUE THREAD

**Issue by yokmama** [ZOIChannel/HideAndSeekPlugin#5]
[Test.zip](https://github.com/ZOIChannel/HideAndSeekPlugin/files/6834497/Test.zip)

**Comment by yokmama** [comment]
PlayerFreezeEvent
＊GameEventは不要
    private static final HandlerList handlers = new HandlerList();
が抽象クラス側に実装されるのでよろしくない

GameWatcher
＊if (p.getFreezeTick() == LIMIT) {
の比較だと、LIMITと同じTickにならない場合（スキップなどにより超えてしまった）、処理がされない問題があるので＜を使う必要がある

＊PlayerFreezeEventをメンバ変数にしてしまっている
PlayerFreezeEventは、イベント発生時に生成し、PlayerFreezeEventにターゲットになるプレイヤーを渡すように修正する必要がある

**Comment by ryosuke0818** [comment]
修正しました
