### ISSUE TITLE
マルチプレイでブロックが固定されない

### ISSUE THREAD

**Issue by ZOIChannel** [ZOIChannel/HideAndSeekPlugin#9]
マルチプレイ時に同時に一人しかブロックが固定されません
あと、不具合で固まることがなさそうならブロックの浮かす量をもう少し少なくしてもいいと思います
(少し浮いているのが見える)

**Comment by ZOIChannel** [comment]
- SeekerがHiderを殴れない
(ブロックの当たり判定はEventManagerの90行目くらいの`if (hider == null) return;`で処理が終了)
(FallingBlockの当たり判定は、FallingBlockを殴ったときにDamageEventが発生しない)
- Hiderのプレイヤー部分に当たり判定があるので、Hider本体に対してのEntityDamageByEntityEventが発生している

**Comment by ryosuke0818** [comment]
・ブロックの当たり判定は等式`(this.block == block)`から
比較メソッド`(this.block.equal(block))`を使うことで修正
・エンティティブロックの当たり判定は別途対策を講じる必要あり

**Comment by ZOIChannel** [comment]
エンティティブロックの当たり判定が厳しそうなら、透明化しているプレイヤーへの攻撃を取得する方法でもいいかもしれません

**Comment by ryosuke0818** [comment]
エンティティブロックに関する議論は別で
